apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    mojix.ops.autorun: "DATE_PLACEHOLDER"
  labels:
    cloud.googleapis.com/location: us-central1
  name: traceability-event-generator
  namespace: '1033743173074'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '2'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: cloud-console
      name: NAME_PLACEHOLDER
    spec:
      containerConcurrency: 80
      containers:
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      serviceAccountName: mrgrt-deployment@margarita-poc.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
